#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=01:00:00
#PBS -N head_pos

# PBS is a computer software that performs job-scheduling
# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana U
#
# This is the main file run by the brainlife.io orchestration system
#
# Author: Franco Pestilli


set -e
set -x

# Make output directory
mkdir -p out_dir

# Run the actual python code
singularity exec docker://brainlifemeeg/mne:1.12.1 python3 main.py

